@extends('layouts.adminLayout.admin-design')
@section('title', 'Add Consultancy')
@section('content')
    @php($selectedRelatedConsultancies = array_map('intval', old('related_consultancy_ids', [])))
    <div class="container-fluid">
        <div class="mb-4"><h2 class="mb-1">Add Consultancy</h2><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.consultancy.index') }}">Consultancy</a></li><li class="breadcrumb-item active">Add Consultancy</li></ol></nav></div>
        @if ($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong></div>@endif
        <form method="POST" action="{{ route('admin.consultancy.store') }}" enctype="multipart/form-data">@csrf
            <section class="card admin-settings-card"><div class="card-header"><h3>Consultancy Information</h3><p>Create the consultancy record as a draft.</p></div><div class="card-body"><div class="row g-4">
                <div class="col-lg-6"><label class="form-label" for="title">Title <span class="text-danger">*</span></label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" type="text" value="{{ old('title') }}" maxlength="255" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><label class="form-label" for="button_label">Button Label <span class="text-danger">*</span></label><input class="form-control @error('button_label') is-invalid @enderror" id="button_label" name="button_label" type="text" value="{{ old('button_label') }}" maxlength="100" placeholder="Book Consultancy" required>@error('button_label')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><label class="form-label" for="image">Image <span class="text-danger">*</span></label><input class="form-control @error('image') is-invalid @enderror" id="image" name="image" type="file" accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp" required><div class="form-text">PNG, JPG, JPEG, or WEBP. Maximum 5 MB.</div>@error('image')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-12"><label class="form-label" for="short_description">Short Description</label><textarea class="form-control @error('short_description') is-invalid @enderror" id="short_description" name="short_description" rows="3">{{ old('short_description') }}</textarea>@error('short_description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-12"><label class="form-label" for="description">Description <span class="text-danger">*</span></label><textarea class="form-control article-editor @error('description') is-invalid @enderror" id="description" name="description" rows="16">{{ old('description') }}</textarea>@error('description')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-4"><label class="form-label" for="duration_type">Duration Type <span class="text-danger">*</span></label><select class="form-select select2 @error('duration_type') is-invalid @enderror" id="duration_type" name="duration_type" required><option value="">Select Duration Type</option>@foreach (\App\Models\Consultancy::DURATION_TYPES as $value => $label)<option value="{{ $value }}" @selected(old('duration_type') === $value)>{{ $label }}</option>@endforeach</select>@error('duration_type')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-4"><label class="form-label" for="duration_value">Duration Value <span class="text-danger">*</span></label><input class="form-control @error('duration_value') is-invalid @enderror" id="duration_value" name="duration_value" type="number" min="1" value="{{ old('duration_value') }}" required>@error('duration_value')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-4"><label class="form-label" for="consultancy_medium">Consultancy Medium <span class="text-danger">*</span></label><select class="form-select select2 @error('consultancy_medium') is-invalid @enderror" id="consultancy_medium" name="consultancy_medium" required><option value="">Select Medium</option>@foreach (\App\Models\Consultancy::MEDIUMS as $value => $label)<option value="{{ $value }}" @selected(old('consultancy_medium') === $value)>{{ $label }}</option>@endforeach</select>@error('consultancy_medium')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><span class="form-label d-block">Visibility</span><div class="d-flex gap-4"><div class="form-check"><input class="form-check-input" id="active_yes" name="isActive" type="radio" value="1" @checked((string) old('isActive', '1') === '1')><label class="form-check-label" for="active_yes">Active</label></div><div class="form-check"><input class="form-check-input" id="active_no" name="isActive" type="radio" value="0" @checked((string) old('isActive', '1') === '0')><label class="form-check-label" for="active_no">Deactive</label></div></div>@error('isActive')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><span class="form-label d-block">Featured</span><div class="d-flex gap-4"><div class="form-check"><input class="form-check-input" id="featured_yes" name="isFeatured" type="radio" value="1" @checked((string) old('isFeatured', '0') === '1')><label class="form-check-label" for="featured_yes">Featured</label></div><div class="form-check"><input class="form-check-input" id="featured_no" name="isFeatured" type="radio" value="0" @checked((string) old('isFeatured', '0') === '0')><label class="form-check-label" for="featured_no">Not Featured</label></div></div>@error('isFeatured')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-12"><label class="form-label" for="related_consultancy_ids">Related Consultancies</label><select class="form-select select2" id="related_consultancy_ids" name="related_consultancy_ids[]" multiple>@foreach ($relatedConsultancies as $relatedConsultancy)<option value="{{ $relatedConsultancy->id }}" @selected(in_array($relatedConsultancy->id, $selectedRelatedConsultancies, true))>{{ $relatedConsultancy->title }} ({{ ucfirst($relatedConsultancy->status) }})</option>@endforeach</select>@error('related_consultancy_ids')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror @error('related_consultancy_ids.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
            </div></div></section>
            <div class="d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.consultancy.index') }}">Cancel</a><button class="btn btn-primary admin-primary-button" type="submit"><i class="fa-solid fa-plus me-2"></i>Add Consultancy</button></div>
        </form>
    </div>
@endsection
