@extends('layouts.adminLayout.admin-design')
@section('title', 'Consultancy Details')
@section('content')
    <div class="container-fluid">
        <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h2 class="mb-1">Consultancy Details</h2><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.consultancy.index') }}">Consultancy</a></li><li class="breadcrumb-item active">Details</li></ol></nav></div><a class="btn btn-outline-secondary" href="{{ route('admin.consultancy.index') }}">Back to Consultancy</a></div>
        @if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
        <section class="card admin-settings-card mb-4"><div class="card-header"><h3>Consultancy Information</h3><p>Complete consultancy and publication overview.</p></div><div class="card-body"><div class="row g-4"><div class="col-lg-3">@if ($consultancy->image)<img class="img-fluid rounded border" src="{{ asset($consultancy->image) }}" alt="{{ $consultancy->title }} image">@else<span class="text-muted">No Consultancy image</span>@endif</div><div class="col-lg-9"><div class="row g-3">@foreach (['Title' => $consultancy->title, 'Button Label' => $consultancy->button_label, 'Duration' => $consultancy->duration_value.' '.($consultancy::DURATION_TYPES[$consultancy->duration_type] ?? $consultancy->duration_type), 'Medium' => $consultancy::MEDIUMS[$consultancy->consultancy_medium] ?? $consultancy->consultancy_medium, 'Featured' => $consultancy->isFeatured ? 'Yes' : 'No', 'Active' => $consultancy->isActive ? 'Yes' : 'No', 'Status' => ucfirst($consultancy->status), 'Published At' => $consultancy->published_at?->format('d M Y, h:i A'), 'Created At' => $consultancy->created_at?->format('d M Y, h:i A'), 'Updated At' => $consultancy->updated_at?->format('d M Y, h:i A')] as $label => $value)<div class="col-md-6"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $value ?: '—' }}</strong></div>@endforeach<div class="col-12"><small class="text-muted d-block">Short Description</small><div class="text-break">{{ $consultancy->short_description ?: '—' }}</div></div></div></div></div></div></section>
        <section class="card admin-settings-card mb-4"><div class="card-header"><h3>Description</h3><p>Rich-text description preview.</p></div><div class="card-body"><div class="article-content-preview">{!! $consultancy->description !!}</div></div></section>
        <section class="card admin-settings-card"><div class="card-header"><h3>Related Consultancies</h3><p>Directional relationships for this Consultancy.</p></div><div class="card-body">@forelse ($consultancy->relatedConsultancies as $relatedConsultancy)<div class="d-flex flex-wrap align-items-center justify-content-between gap-3 border-bottom py-3"><div><strong>{{ $relatedConsultancy->title }}</strong><span class="badge text-bg-{{ $relatedConsultancy->status === \App\Models\Consultancy::STATUS_PUBLISHED ? 'success' : 'secondary' }} ms-2">{{ ucfirst($relatedConsultancy->status) }}</span></div>@can('consultancies.related.remove')<form method="POST" action="{{ route('admin.consultancy.related.remove', ['consultancy' => $consultancy->id, 'relatedConsultancy' => $relatedConsultancy->id]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit" data-delete-confirm data-delete-title="Remove this related Consultancy?">Remove</button></form>@endcan</div>@empty<span class="text-muted">No related Consultancies.</span>@endforelse</div></section>
    </div>
@endsection
