@extends('layouts.adminLayout.admin-design')
@section('title', 'Add Article')
@section('content')
    @php
        $selectedCategoryId = old('category_id');
        $selectedAuthorId = old('author_id');
        $selectedRelatedArticles = array_map('intval', old('related_article_ids', []));
    @endphp
    <div class="container-fluid">
        <div class="mb-4"><h2 class="mb-1">Add Article</h2><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.article.index') }}">Articles</a></li><li class="breadcrumb-item active">Add Article</li></ol></nav></div>
        @if ($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong></div>@endif
        <form method="POST" action="{{ route('admin.article.store') }}" enctype="multipart/form-data">@csrf
            <section class="card admin-settings-card"><div class="card-header"><h3>Article Information</h3><p>Create the editorial record as a draft.</p></div><div class="card-body"><div class="row g-4">
                <div class="col-lg-4"><label class="form-label" for="language">Language <span class="text-danger">*</span></label><select class="form-select select2 @error('language') is-invalid @enderror" id="language" name="language" data-magazine-language required><option value="">Select Language</option>@foreach ($languages as $language)<option value="{{ $language->code }}" @selected(old('language') === $language->code)>{{ $language->name ?? $language->code }}</option>@endforeach</select>@error('language')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-5"><label class="form-label" for="title">Title <span class="text-danger">*</span></label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" type="text" value="{{ old('title') }}" maxlength="255" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-4"><label class="form-label" for="publish_date">Publish Date</label><input class="form-control @error('publish_date') is-invalid @enderror" id="publish_date" name="publish_date" type="date" value="{{ old('publish_date') }}">@error('publish_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-8"><label class="form-label" for="image">Article Image</label><input class="form-control @error('image') is-invalid @enderror" id="image" name="image" type="file" accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp"><div class="form-text">PNG, JPG, JPEG, or WEBP. Maximum 5 MB.</div>@error('image')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-12"><label class="form-label" for="short_description">Short Description</label><textarea class="form-control @error('short_description') is-invalid @enderror" id="short_description" name="short_description" rows="3">{{ old('short_description') }}</textarea>@error('short_description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-12"><label class="form-label" for="article">Article Content <span class="text-danger">*</span></label><textarea class="form-control article-editor @error('article') is-invalid @enderror" id="article" name="article" rows="16">{{ old('article') }}</textarea>@error('article')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-4"><label class="form-label" for="category_id">Category</label><select class="form-select select2 @error('category_id') is-invalid @enderror" id="category_id" name="category_id" data-magazine-language-options><option value="">Select Category</option>@foreach ($categories as $category)<option value="{{ $category->id }}" data-language="{{ $category->language }}" @selected((string) $selectedCategoryId === (string) $category->id)>{{ $category->name ?? 'Untitled' }} ({{ $category->language }})</option>@endforeach</select>@error('category_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-4"><label class="form-label" for="author_id">Author</label><select class="form-select select2 @error('author_id') is-invalid @enderror" id="author_id" name="author_id"><option value="">Select Author</option>@foreach ($authors as $author)<option value="{{ $author->id }}" @selected((string) $selectedAuthorId === (string) $author->id)>{{ $author->name ?? 'Untitled' }}</option>@endforeach</select>@error('author_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-12"><label class="form-label" for="related_article_ids">Related Articles</label><select class="form-select select2" id="related_article_ids" name="related_article_ids[]" data-magazine-language-options multiple>@foreach ($relatedArticles as $relatedArticle)<option value="{{ $relatedArticle->id }}" data-language="{{ $relatedArticle->language }}" @selected(in_array($relatedArticle->id, $selectedRelatedArticles, true))>{{ $relatedArticle->title ?? 'Untitled' }}@if ($relatedArticle->issue_number) — {{ $relatedArticle->issue_number }}@endif ({{ $relatedArticle->language }})</option>@endforeach</select>@error('related_article_ids')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror @error('related_article_ids.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><span class="form-label d-block">Free Access</span><div class="d-flex gap-4"><div class="form-check"><input class="form-check-input" id="free_yes" name="isFree" type="radio" value="1" data-free-access-toggle @checked((string) old('isFree', '0') === '1')><label class="form-check-label" for="free_yes">Free</label></div><div class="form-check"><input class="form-check-input" id="free_no" name="isFree" type="radio" value="0" data-free-access-toggle @checked((string) old('isFree', '0') === '0')><label class="form-check-label" for="free_no">Paid</label></div></div>@error('isFree')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6 {{ (string) old('isFree', '0') === '1' ? '' : 'd-none' }}" data-free-until-field><label class="form-label" for="free_until">Free Until</label><input class="form-control @error('free_until') is-invalid @enderror" id="free_until" name="free_until" type="date" value="{{ old('free_until') }}" min="{{ now()->toDateString() }}" data-free-until-input @disabled((string) old('isFree', '0') !== '1')><div class="form-text">Optional. Leave empty for permanently free access.</div>@error('free_until')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><span class="form-label d-block">Featured</span><div class="d-flex gap-4"><div class="form-check"><input class="form-check-input" id="featured_yes" name="isFeatured" type="radio" value="1" @checked((string) old('isFeatured', '0') === '1')><label class="form-check-label" for="featured_yes">Yes</label></div><div class="form-check"><input class="form-check-input" id="featured_no" name="isFeatured" type="radio" value="0" @checked((string) old('isFeatured', '0') === '0')><label class="form-check-label" for="featured_no">No</label></div></div>@error('isFeatured')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
            </div></div></section>
            <section class="card admin-settings-card"><div class="card-header"><h3>Homepage &amp; Display Settings</h3><p>Choose where this Article can appear and whether its visit counter may be shown.</p></div><div class="card-body"><div class="row g-4">
                @foreach (['show_on_latest' => 'Show On Latest', 'show_on_editorial_center' => 'Show On Editorial Center', 'show_on_editorial_featured' => 'Show On Editorial Featured', 'show_visit_counter' => 'Show Visit Counter'] as $field => $label)
                    <div class="col-md-6"><span class="form-label d-block">{{ $label }}</span><div class="d-flex gap-4"><div class="form-check"><input class="form-check-input" id="{{ $field }}_yes" name="{{ $field }}" type="radio" value="1" @checked((string) old($field, '0') === '1')><label class="form-check-label" for="{{ $field }}_yes">Yes</label></div><div class="form-check"><input class="form-check-input" id="{{ $field }}_no" name="{{ $field }}" type="radio" value="0" @checked((string) old($field, '0') === '0')><label class="form-check-label" for="{{ $field }}_no">No</label></div></div>@error($field)<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                @endforeach
            </div></div></section>
            <section class="card admin-settings-card"><div class="card-header"><h3>SEO Settings</h3><p>Title and slug are synchronized automatically.</p></div><div class="card-body"><div class="row g-4"><div class="col-lg-6"><label class="form-label" for="keywords">Meta Keywords</label><textarea class="form-control @error('keywords') is-invalid @enderror" id="keywords" name="keywords" rows="3">{{ old('keywords') }}</textarea>@error('keywords')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-lg-6"><label class="form-label" for="meta_description">Meta Description</label><textarea class="form-control @error('meta_description') is-invalid @enderror" id="meta_description" name="meta_description" rows="3">{{ old('meta_description') }}</textarea>@error('meta_description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div></section>
            <div class="d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.article.index') }}">Cancel</a><button class="btn btn-primary admin-primary-button" type="submit"><i class="fa-solid fa-plus me-2"></i>Add Article</button></div>
        </form>
    </div>
@endsection
