@extends('layouts.adminLayout.admin-design')
@section('title', 'Article Details')
@section('content')
    <div class="container-fluid">
        <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h2 class="mb-1">Article Details</h2><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.article.index') }}">Articles</a></li><li class="breadcrumb-item active">Details</li></ol></nav></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.article.index') }}"><i class="fa-solid fa-arrow-left me-2"></i>Back to Articles</a>@can('articles.edit')<a class="btn btn-outline-primary" href="{{ route('admin.article.edit', ['id' => $article->id]) }}"><i class="fa-solid fa-pen-to-square me-2"></i>Edit</a>@endcan @can('articles.publish')@if ($article->status !== 'published')<form method="POST" action="{{ route('admin.article.publish', ['id' => $article->id]) }}">@csrf<button class="btn btn-success" type="submit" data-publish-confirm data-publish-title="Publish this Article?" data-publish-text="Once published it will be eligible for frontend display."><i class="fa-solid fa-upload me-2"></i>Publish</button></form>@endif @endcan</div></div>
        @if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
        @if (session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
        <section class="card admin-settings-card"><div class="card-header"><h3>Main Article Information</h3><p>Complete editorial and publication overview.</p></div><div class="card-body"><div class="row g-4"><div class="col-lg-3">@if ($article->image)<img class="img-fluid rounded border" src="{{ asset($article->image) }}" alt="{{ $article->title }} image">@else<span class="text-muted">No Article image</span>@endif</div><div class="col-lg-9"><div class="row g-3">@foreach (['Title' => $article->title, 'Language' => $languageName ?? $article->language, 'Issue Number' => $article->issue_number, 'Publish Date' => $article->publish_date?->format('d M Y'), 'Free' => $article->isFree ? 'Yes' : 'No', 'Featured' => $article->isFeatured ? 'Yes' : 'No', 'Active' => $article->isActive ? 'Yes' : 'No', 'Status' => ucfirst($article->status ?? 'draft'), 'Published At' => $article->published_at?->format('d M Y, h:i A'), 'Created At' => $article->created_at?->format('d M Y, h:i A'), 'Updated At' => $article->updated_at?->format('d M Y, h:i A')] as $label => $value)<div class="col-md-6"><small class="text-muted d-block">{{ $label }}</small><strong>{{ $value ?: '—' }}</strong></div>@endforeach<div class="col-12"><small class="text-muted d-block">Short Description</small><div class="text-break">{{ $article->short_description ?: '—' }}</div></div></div></div></div></div></section>
        <section class="card admin-settings-card"><div class="card-header"><h3>Article Content</h3><p>Rich-text content preview.</p></div><div class="card-body"><div class="article-content-preview">{!! $article->article !!}</div></div></section>
        <section class="card admin-settings-card"><div class="card-header"><h3>Relationships</h3><p>Connected categories and authors.</p></div><div class="card-body"><div class="row g-4"><div class="col-lg-6"><h4 class="h6">Categories</h4>@forelse ($article->categories as $category)<span class="badge text-bg-light border me-1 mb-1">{{ $category->name ?? 'Untitled' }}</span>@empty<span class="text-muted">None</span>@endforelse</div><div class="col-lg-6"><h4 class="h6">Authors</h4>@forelse ($article->authors as $author)<span class="badge text-bg-light border me-1 mb-1">{{ $author->name ?? 'Untitled' }}</span>@empty<span class="text-muted">None</span>@endforelse</div></div></div></section>
        <section class="card admin-settings-card"><div class="card-header"><h3>Related Articles</h3><p>Directional Article relationships managed for this record.</p></div><div class="card-body"><div class="row g-3">@forelse ($article->relatedArticles as $relatedArticle)<div class="col-xl-4 col-md-6"><div class="border rounded p-3 h-100 d-flex gap-3"><div class="flex-shrink-0">@if ($relatedArticle->image)<img class="rounded border object-fit-cover" src="{{ asset($relatedArticle->image) }}" alt="{{ $relatedArticle->title }} image" width="64" height="84">@else<div class="bg-light border rounded p-3 text-muted"><i class="fa-solid fa-newspaper"></i></div>@endif</div><div class="flex-grow-1"><h4 class="h6 text-break mb-1">{{ $relatedArticle->title ?? 'Untitled Article' }}</h4><div class="small text-muted mb-1">Issue: {{ $relatedArticle->issue_number ?: '—' }}</div><span class="badge text-bg-{{ $relatedArticle->status === 'published' ? 'success' : 'secondary' }} mb-3">{{ ucfirst($relatedArticle->status ?? 'draft') }}</span><div class="d-flex flex-wrap gap-2"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.article.show', ['id' => $relatedArticle->id]) }}"><i class="fa-solid fa-eye me-1"></i>View</a>@can('articles.related.remove')<form method="POST" action="{{ route('admin.article.related.remove', ['article' => $article->id, 'relatedArticle' => $relatedArticle->id]) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit" data-delete-confirm data-delete-title="Remove this related Article?" data-delete-text="Only the relationship will be removed. Neither Article will be deleted."><i class="fa-solid fa-link-slash me-1"></i>Remove</button></form>@endcan</div></div></div></div>@empty<div class="col-12"><p class="text-muted mb-0">No related Articles selected.</p></div>@endforelse</div></div></section>
        <section class="card admin-settings-card"><div class="card-header"><h3>SEO</h3><p>Connected Article MetaTag record.</p></div><div class="card-body"><div class="row g-3"><div class="col-lg-6"><small class="text-muted d-block">Meta Title</small><div>{{ $metaTag?->title ?? '—' }}</div></div><div class="col-lg-6"><small class="text-muted d-block">Slug</small><div>{{ $metaTag?->slug_url ?? '—' }}</div></div><div class="col-lg-6"><small class="text-muted d-block">Keywords</small><div class="text-break">{{ $metaTag?->keywords ?? '—' }}</div></div><div class="col-lg-6"><small class="text-muted d-block">Canonical</small><div class="text-break">{{ $metaTag?->canonical_url ?: 'Auto-generated from current domain, Article route, and slug' }}</div></div><div class="col-12"><small class="text-muted d-block">Meta Description</small><div class="text-break">{{ $metaTag?->description ?? '—' }}</div></div></div></div></section>
        <div class="d-flex flex-wrap justify-content-between gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.article.index') }}"><i class="fa-solid fa-arrow-left me-2"></i>Back to Articles</a>@can('articles.publish')@if ($article->status !== 'published')<form method="POST" action="{{ route('admin.article.publish', ['id' => $article->id]) }}">@csrf<button class="btn btn-success" type="submit" data-publish-confirm data-publish-title="Publish this Article?" data-publish-text="Once published it will be eligible for frontend display."><i class="fa-solid fa-upload me-2"></i>Publish</button></form>@endif @endcan</div>
    </div>
@endsection
