@extends('layouts.adminLayout.admin-design')
@section('title', 'Edit Subscription Plan')
@section('content')
    @php($selectedType = old('subscription_type_id', $plan->subscriptionTypes->first()?->id))
    @php($selectedVideoIds = array_map('strval', old('video_ids', $plan->videos->pluck('id')->all())))
    <div class="container-fluid">
        <div class="mb-4"><h2 class="mb-1">Edit Subscription Plan</h2><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.subscription-plan.index') }}">Subscription Plans</a></li><li class="breadcrumb-item active">Edit</li></ol></nav></div>
        @if ($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong></div>@endif
        <form method="POST" action="{{ route('admin.subscription-plan.update', ['id' => $plan->id]) }}">@csrf
            <section class="card admin-settings-card"><div class="card-header"><h3>Plan Information</h3><p>Update the plan without changing its product type.</p></div><div class="card-body"><div class="row g-4">
                <div class="col-lg-6"><label class="form-label" for="name">Plan Name <span class="text-danger">*</span></label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $plan->name) }}">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><label class="form-label" for="subscription_type_id">Subscription Type <span class="text-danger">*</span></label><select class="form-select select2" id="subscription_type_id" name="subscription_type_id"><option value="">Select Subscription Type</option>@foreach($subscriptionTypes as $type)<option value="{{ $type->id }}" @selected((string) $selectedType === (string) $type->id)>{{ $type->name }}</option>@endforeach</select>@error('subscription_type_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><label class="form-label" for="currency_id">Currency <span class="text-danger">*</span></label><select class="form-select select2" id="currency_id" name="currency_id"><option value="">Select Currency</option>@foreach($currencies as $currency)<option value="{{ $currency->id }}" @selected((string) old('currency_id', $plan->currency_id) === (string) $currency->id)>{{ $currency->code }} - {{ $currency->name }}</option>@endforeach</select>@error('currency_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-lg-6"><label class="form-label" for="price">Price <span class="text-danger">*</span></label><input class="form-control @error('price') is-invalid @enderror" id="price" name="price" type="number" min="0" step="0.01" value="{{ old('price', $plan->price) }}">@error('price')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-md-6"><label class="form-label" for="duration_value">Duration Value <span class="text-danger">*</span></label><input class="form-control @error('duration_value') is-invalid @enderror" id="duration_value" name="duration_value" type="number" min="1" value="{{ old('duration_value', $plan->duration_value) }}">@error('duration_value')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-md-6"><label class="form-label" for="duration_unit">Duration Unit <span class="text-danger">*</span></label><select class="form-select select2" id="duration_unit" name="duration_unit">@foreach(['day'=>'Day','month'=>'Month','year'=>'Year'] as $value=>$label)<option value="{{ $value }}" @selected(old('duration_unit', $plan->duration_unit) === $value)>{{ $label }}</option>@endforeach</select>@error('duration_unit')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-md-6"><label class="form-label" for="discount_type">Discount Type</label><select class="form-select select2" id="discount_type" name="discount_type"><option value="">No Discount</option><option value="fixed" @selected(old('discount_type', $plan->discount_type) === 'fixed')>Fixed</option><option value="percentage" @selected(old('discount_type', $plan->discount_type) === 'percentage')>Percentage</option></select>@error('discount_type')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-md-6"><label class="form-label" for="discount_value">Discount Value</label><input class="form-control @error('discount_value') is-invalid @enderror" id="discount_value" name="discount_value" type="number" min="0" step="0.01" value="{{ old('discount_value', $plan->discount_value) }}">@error('discount_value')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
                <div class="col-12"><label class="form-label" for="video_ids">Included Videos</label><select class="form-select select2 @error('video_ids.*') is-invalid @enderror" id="video_ids" name="video_ids[]" multiple>@foreach($videos as $video)<option value="{{ $video->id }}" @selected(in_array((string) $video->id, $selectedVideoIds, true))>{{ $video->title }}{{ ! $video->is_active && $video->status !== \App\Models\Video::STATUS_PUBLISHED ? ' — Existing: Inactive / Draft' : (! $video->is_active ? ' — Existing: Inactive' : ($video->status !== \App\Models\Video::STATUS_PUBLISHED ? ' — Existing: Draft' : '')) }}</option>@endforeach</select><div class="form-text">Only active, published Videos can be newly included. Existing unavailable assignments remain selected until you remove them.</div>@error('video_ids')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror @error('video_ids.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
                <div class="col-12"><span class="form-label d-block">Status <span class="text-danger">*</span></span><div class="d-flex gap-4"><label class="form-check"><input class="form-check-input" name="isActive" type="radio" value="1" @checked((string) old('isActive', (int) $plan->isActive) === '1')> Active</label><label class="form-check"><input class="form-check-input" name="isActive" type="radio" value="0" @checked((string) old('isActive', (int) $plan->isActive) === '0')> Deactive</label></div>@error('isActive')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
            </div></div></section>
            <div class="d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.subscription-plan.index') }}">Cancel</a><button class="btn btn-primary admin-primary-button" type="submit"><i class="fa-solid fa-floppy-disk me-2"></i>Update Subscription Plan</button></div>
        </form>
    </div>
@endsection
