<div class="row g-4">
    <div class="col-lg-6"><label class="form-label">Title *</label><input class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $course->title ?? '') }}" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-lg-6"><label class="form-label">Button Label *</label><input class="form-control @error('button_label') is-invalid @enderror" name="button_label" maxlength="100" value="{{ old('button_label', $course->button_label ?? '') }}" required>@error('button_label')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-lg-6"><label class="form-label">Image {{ isset($course) ? '' : '*' }}</label>@if (isset($course) && $course->image)<div class="mb-2"><img class="admin-current-image" src="{{ asset($course->image) }}" alt="Current Course image"></div>@endif<input class="form-control @error('image') is-invalid @enderror" name="image" type="file" accept=".png,.jpg,.jpeg,.webp" @if (! isset($course)) required @endif>@error('image')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label">Short Description</label><textarea class="form-control" name="short_description" rows="3">{{ old('short_description', $course->short_description ?? '') }}</textarea></div>
    <div class="col-12"><label class="form-label">Description *</label><textarea class="form-control article-editor @error('description') is-invalid @enderror" name="description" rows="16" required>{{ old('description', $course->description ?? '') }}</textarea>@error('description')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="col-lg-6"><label class="form-label">Duration Type *</label><select class="form-select select2" name="duration_type" required><option value="">Select Duration Type</option>@foreach (\App\Models\Course::DURATION_TYPES as $value => $label)<option value="{{ $value }}" @selected(old('duration_type', $course->duration_type ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-lg-6"><label class="form-label">Duration Value *</label><input class="form-control" name="duration_value" type="number" min="1" value="{{ old('duration_value', $course->duration_value ?? '') }}" required></div>
    <div class="col-lg-6"><span class="form-label d-block">Visibility</span><div class="form-check form-check-inline"><input class="form-check-input" id="activeYes" name="isActive" type="radio" value="1" @checked((string) old('isActive', isset($course) ? (int) $course->isActive : 1) === '1')><label class="form-check-label" for="activeYes">Active</label></div><div class="form-check form-check-inline"><input class="form-check-input" id="activeNo" name="isActive" type="radio" value="0" @checked((string) old('isActive', isset($course) ? (int) $course->isActive : 1) === '0')><label class="form-check-label" for="activeNo">Deactive</label></div></div>
    <div class="col-lg-6"><span class="form-label d-block">Featured</span><div class="form-check form-check-inline"><input class="form-check-input" id="featuredYes" name="isFeatured" type="radio" value="1" @checked((string) old('isFeatured', isset($course) ? (int) $course->isFeatured : 0) === '1')><label class="form-check-label" for="featuredYes">Featured</label></div><div class="form-check form-check-inline"><input class="form-check-input" id="featuredNo" name="isFeatured" type="radio" value="0" @checked((string) old('isFeatured', isset($course) ? (int) $course->isFeatured : 0) === '0')><label class="form-check-label" for="featuredNo">Not Featured</label></div></div>
    <div class="col-12"><label class="form-label">Related Courses</label><select class="form-select select2" name="related_course_ids[]" multiple>@foreach ($relatedCourses as $relatedCourse)<option value="{{ $relatedCourse->id }}" @selected(in_array($relatedCourse->id, $selectedRelatedCourseIds ?? old('related_course_ids', [])))>{{ $relatedCourse->title }} ({{ ucfirst($relatedCourse->status) }})</option>@endforeach</select>@error('related_course_ids')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
</div>
