@extends('layouts.adminLayout.admin-design')
@section('title', 'Edit Membership')
@section('content')
    @php($selectedTypes = array_map('strval', old('subscription_type_ids', $membership->subscriptionTypes->pluck('id')->all())))
    <div class="container-fluid"><div class="mb-4"><h2 class="mb-1">Edit Membership</h2><nav aria-label="breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item"><a href="{{ route('admin.membership.index') }}">Memberships</a></li><li class="breadcrumb-item active">Edit</li></ol></nav></div>
        @if($errors->any())<div class="alert alert-danger"><strong>Please correct the highlighted fields.</strong></div>@endif
        <form method="POST" action="{{ route('admin.membership.update', ['id' => $membership->id]) }}">@csrf<section class="card admin-settings-card"><div class="card-header"><h3>Membership Information</h3><p>Update membership details and included subscription types.</p></div><div class="card-body"><div class="row g-4">
            <div class="col-lg-6"><label class="form-label" for="name">Membership Name <span class="text-danger">*</span></label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $membership->name) }}">@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-lg-6"><label class="form-label" for="subscription_type_ids">Subscription Types <span class="text-danger">*</span></label><select class="form-select select2" id="subscription_type_ids" name="subscription_type_ids[]" multiple>@foreach($subscriptionTypes as $type)<option value="{{ $type->id }}" @selected(in_array((string) $type->id, $selectedTypes, true))>{{ $type->name }}</option>@endforeach</select>@error('subscription_type_ids')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror @error('subscription_type_ids.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
            <div class="col-lg-6"><label class="form-label" for="currency_id">Currency <span class="text-danger">*</span></label><select class="form-select select2" id="currency_id" name="currency_id"><option value="">Select Currency</option>@foreach($currencies as $currency)<option value="{{ $currency->id }}" @selected((string) old('currency_id', $membership->currency_id) === (string) $currency->id)>{{ $currency->code }} - {{ $currency->name }}</option>@endforeach</select>@error('currency_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
            <div class="col-lg-6"><label class="form-label" for="price">Price <span class="text-danger">*</span></label><input class="form-control @error('price') is-invalid @enderror" id="price" name="price" type="number" min="0" step="0.01" value="{{ old('price', $membership->price) }}">@error('price')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="duration_value">Duration Value <span class="text-danger">*</span></label><input class="form-control @error('duration_value') is-invalid @enderror" id="duration_value" name="duration_value" type="number" min="1" value="{{ old('duration_value', $membership->duration_value) }}">@error('duration_value')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="duration_unit">Duration Unit <span class="text-danger">*</span></label><select class="form-select select2" id="duration_unit" name="duration_unit">@foreach(['day'=>'Day','month'=>'Month','year'=>'Year'] as $value=>$label)<option value="{{ $value }}" @selected(old('duration_unit', $membership->duration_unit) === $value)>{{ $label }}</option>@endforeach</select>@error('duration_unit')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="discount_type">Discount Type</label><select class="form-select select2" id="discount_type" name="discount_type"><option value="">No Discount</option><option value="fixed" @selected(old('discount_type', $membership->discount_type) === 'fixed')>Fixed</option><option value="percentage" @selected(old('discount_type', $membership->discount_type) === 'percentage')>Percentage</option></select>@error('discount_type')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="discount_value">Discount Value</label><input class="form-control @error('discount_value') is-invalid @enderror" id="discount_value" name="discount_value" type="number" min="0" step="0.01" value="{{ old('discount_value', $membership->discount_value) }}">@error('discount_value')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-12"><span class="form-label d-block">Status <span class="text-danger">*</span></span><div class="d-flex gap-4"><label class="form-check"><input class="form-check-input" name="isActive" type="radio" value="1" @checked((string) old('isActive', (int) $membership->isActive) === '1')> Active</label><label class="form-check"><input class="form-check-input" name="isActive" type="radio" value="0" @checked((string) old('isActive', (int) $membership->isActive) === '0')> Deactive</label></div>@error('isActive')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
        </div></div></section><div class="d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.membership.index') }}">Cancel</a><button class="btn btn-primary admin-primary-button" type="submit"><i class="fa-solid fa-floppy-disk me-2"></i>Update Membership</button></div></form>
    </div>
@endsection
