<?php

return [
    'guard' => 'web',
    'access_permission' => 'admin.access',
    'system_roles' => [
        'super-admin' => 'Super Admin',
        'user' => 'User',
        'consultant' => 'Consultant',
    ],
    'modules' => [
        'dashboard' => ['label' => 'Dashboard', 'group' => 'Administration', 'actions' => ['view' => 'View']],
        'site-analytics' => ['label' => 'Site Analytics', 'group' => 'Administration', 'actions' => ['view' => 'View', 'export' => 'Export']],
        'contacts' => ['label' => 'Contact Messages', 'group' => 'Administration', 'actions' => ['view' => 'View', 'delete' => 'Delete']],
        'newsletter-subscribers' => ['label' => 'Newsletter Subscribers', 'group' => 'Administration', 'actions' => ['view' => 'View', 'edit' => 'Re-sync']],
        'newsletter-campaigns' => ['label' => 'Newsletter Campaigns', 'group' => 'Administration', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete', 'send' => 'Send']],
        'ask-questions' => ['label' => 'Ask Questions', 'group' => 'Administration', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'change-password' => ['label' => 'Change Password', 'group' => 'Administration', 'actions' => ['view' => 'View', 'edit' => 'Update']],
        'general-settings' => ['label' => 'General Settings', 'group' => 'Administration', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'sliders' => ['label' => 'Sliders', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'banners' => ['label' => 'Banners', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'ads' => ['label' => 'Ads', 'group' => 'Monetization', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'ad-requests' => ['label' => 'Advertising Requests', 'group' => 'Monetization', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'home-headings' => ['label' => 'Home Headings', 'group' => 'Website', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'home-article' => ['label' => 'Home Article', 'group' => 'Website', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'taza-shumara' => ['label' => 'Taza Shumara', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'home-cards' => ['label' => 'Home Cards', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'home-sections' => ['label' => 'Home Sections', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'services' => ['label' => 'Services', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'privacy-policy' => ['label' => 'Privacy Policy', 'group' => 'Website', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'terms-conditions' => ['label' => 'Terms & Conditions', 'group' => 'Website', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'disclaimer' => ['label' => 'Disclaimer', 'group' => 'Website', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'abouts' => ['label' => 'About', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'faqs' => ['label' => 'FAQs', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'faq-categories' => ['label' => 'FAQ Categories', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'authors' => ['label' => 'Authors', 'group' => 'Content Setup', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'author-settings' => ['label' => 'Author Settings', 'group' => 'Content Setup', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'users' => ['label' => 'Users', 'group' => 'User Management', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'roles' => ['label' => 'Roles', 'group' => 'User Management', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'tags' => ['label' => 'Tags', 'group' => 'Content Setup', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'categories' => ['label' => 'Categories', 'group' => 'Content Setup', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'currency' => ['label' => 'Currency', 'group' => 'System Masters', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'subscription-plans' => ['label' => 'Subscription Plans', 'group' => 'Subscriptions', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'payment-accounts' => ['label' => 'Payment Accounts', 'group' => 'Subscriptions', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'memberships' => ['label' => 'Memberships', 'group' => 'Subscriptions', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
        'user-subscriptions' => ['label' => 'User Subscriptions', 'group' => 'Subscriptions', 'actions' => ['view' => 'View', 'approve' => 'Approve Payment', 'reject' => 'Reject Payment']],
        'subscription-reminder-settings' => ['label' => 'Subscription Reminder Settings', 'group' => 'Subscriptions', 'actions' => ['view' => 'View', 'edit' => 'Edit']],
        'magazines' => [
            'label' => 'Magazines', 'group' => 'Content Setup',
            'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete', 'publish' => 'Publish', 'pdf.view' => 'View PDF', 'pdf.download' => 'Download PDF', 'related.remove' => 'Remove Related Magazine'],
        ],
        'articles' => [
            'label' => 'Articles', 'group' => 'Content Setup',
            'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete', 'publish' => 'Publish', 'related.remove' => 'Remove Related Article'],
        ],
        'consultancies' => [
            'label' => 'Consultancy', 'group' => 'Content Setup',
            'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete', 'publish' => 'Publish', 'related.remove' => 'Remove Related Consultancy'],
        ],
        'courses' => [
            'label' => 'Courses', 'group' => 'Content Setup',
            'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete', 'publish' => 'Publish', 'related.remove' => 'Remove Related Course'],
        ],
        'videos' => ['label' => 'Videos', 'group' => 'Content Setup', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete', 'publish' => 'Publish']],
        'meta-tags' => ['label' => 'SEO / Meta Tags', 'group' => 'Website', 'actions' => ['view' => 'View', 'create' => 'Create', 'edit' => 'Edit', 'delete' => 'Delete']],
    ],
];
